Implement a least breaking approach to slash commands
iDevision/enhanced-discord.py pull request #39
Opened 2021-08-31 18:51 UTC by Gnome-py

## Summary

This PR implements a system on top of ext.commands for slash commands allowing for minimal breakage by constructing fake message objects `on_interaction`, it still requires documentation and much debugging, so I am marking as a draft. I have also run the `reindent` tool on the repo, to get rid of random whitespace and non-standard indentation.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-09-01 10:39 UTC, Gnome-py commented on discord/ext/commands/help.py
> +            await interaction.response.send_message("Sent help to your DMs!", ephemeral=True)
if this isn't done by the lib, the interaction fails (no response in the channel), as this is the default help command I thought it appropriate.

2021-09-01 10:40 UTC, Gnome-py commented on discord/ext/commands/bot.py
> +            self.slash_command_guild = options.get('slash_command_guild', None)
resolved in #bikeshedding

2021-09-01 10:42 UTC, Gnome-py commented on discord/client.py
> +        A coroutine to be called to setup the bot, by default this is blank.
Bot is used in other docstrings throughout Client, such as `clear` and `create_guild`.

2021-09-01 10:46 UTC, isaa-ctaylor commented on discord/ext/commands/bot.py
> +            self.slash_command_guild = options.get('slash_command_guild', None)
I think the idea was to discourage use of guild slash commands where global slash commands could be used, then have a kwarg in command deco for specific guilds:
![image](https://user-images.githubusercontent.com/64303279/131658493-f385921a-a3c8-4154-b095-8fb1f8575e64.png)

2021-09-01 10:48 UTC, Gnome-py commented on discord/ext/commands/bot.py
> +            self.slash_command_guild = options.get('slash_command_guild', None)
yes, maybe I marked resolved prematurely

2021-09-01 10:53 UTC, Gnome-py commented on discord/ext/commands/bot.py
> +    async def setup(self):
needs access to `self.application_id or (await self.application_info())` which are from discord.Client, if you can think of a better way to do it let me know

2021-09-01 13:47 UTC, Gnome-py commented on discord/ext/commands/bot.py
>      """Represents a discord bot.
Added, alongside docs for `message_command` and `slash_command` in the command decorators.

2021-09-01 16:32 UTC, Gnome-py commented on discord/ext/commands/bot.py
> +            self.slash_command_guild = options.get('slash_command_guild', None)
decided to do both

2021-09-02 17:29 UTC, Daggy1234 requested changes
I'll help with tthe typing later, but tons of `type:ignore`

2021-09-02 17:29 UTC, Daggy1234 commented on discord/ext/commands/bot.py
> +        self: discord.Message = cls(channel=interaction.channel, id=interaction.id) # type: ignore
Nitpick, but I think avoiding `# type :ignore` is a good precedent

2021-09-02 17:29 UTC, Daggy1234 commented on discord/ext/commands/bot.py
> +            assert guild is not None
better to `if` and raise an error, I think that  comes  to api design. But I think a better error for the user is necessary instead of an simple assertionerror

2021-09-02 17:29 UTC, Daggy1234 commented on discord/ext/commands/bot.py
> +    async def on_interaction(self, interaction: discord.Interaction):
Docstring for function?

2021-09-02 17:29 UTC, Daggy1234 commented on discord/ext/commands/context.py
> +        ------------
Content not in func docstring

2021-09-02 17:29 UTC, Daggy1234 commented on discord/ext/commands/core.py
> +            raise ValueError(f"{self.qualified_name} is too deeply nested for slash commands!")
ValueError? use an ext.command error right like the registration error

2021-09-02 17:29 UTC, Daggy1234 commented on discord/state.py
> +            raise TypeError(f'intents parameter must be Intent not {type(intents)!r}')
Reads better as "Parameter 'intents' must be of :class:`discord.Intent`"

2021-09-02 19:28 UTC, Gnome-py commented on discord/ext/commands/bot.py
> +        self: discord.Message = cls(channel=interaction.channel, id=interaction.id) # type: ignore
where would I put it then, I have to somewhere to make the fake message into a discord.Message for typing purposes

2021-09-02 19:28 UTC, Gnome-py commented on discord/ext/commands/bot.py
> +            assert guild is not None
this is a situation that should never happen, and the assert is only for typing purposes, None was popped from the dict above.

2021-09-02 19:28 UTC, Gnome-py commented on discord/ext/commands/context.py
> +        ------------
Content is from `abc.Messageable.send` and 
>  This function takes all the parameters of :meth:\`.abc.Messageable.send\`

2021-09-02 19:28 UTC, Gnome-py commented on discord/state.py
> +            raise TypeError(f'intents parameter must be Intent not {type(intents)!r}')
Not a change from this PR, weird git stuff is going on.

2021-09-02 20:28 UTC, Gnome-py commented on discord/client.py
> +        it has connected to the Websocket, overwrite this coroutine.
Resolved in 8a779ef595a8c167309110eeb4de28b8e0932dc6

2021-09-02 20:28 UTC, Gnome-py commented on discord/ext/commands/bot.py
> +    async def on_interaction(self, interaction: discord.Interaction):
Resolved in 8a779ef595a8c167309110eeb4de28b8e0932dc6

2021-09-02 20:28 UTC, Gnome-py commented on discord/ext/commands/core.py
> +            raise ValueError(f"{self.qualified_name} is too deeply nested for slash commands!")
Resolved in 8a779ef595a8c167309110eeb4de28b8e0932dc6

2021-09-11 22:31 UTC, IAmTomahawkx requested changes

2021-09-11 22:31 UTC, IAmTomahawkx commented on discord/ext/commands/bot.py
> +            raise TypeError("Both message_commands and slash_commands are disabled.")
TypeError isnt the right type of error to raise here.
Consider ValueError

2021-09-11 22:31 UTC, IAmTomahawkx commented on discord/ext/commands/bot.py
> +                channel = await interaction.guild.fetch_channel(interaction.channel_id)
try pulling from cache first here maybe?

2021-09-11 22:31 UTC, IAmTomahawkx commented on discord/ext/commands/core.py
> +            raise TypeError("Cannot set specific guilds for a subcommand. They are inherited from the top level group.")
This also should be a ValueError

2021-09-12 10:46 UTC, Gnome-py commented on discord/ext/commands/bot.py
> +                channel = await interaction.guild.fetch_channel(interaction.channel_id)
interaction.channel is a property that does a cache lookup using the ID, if it is None or PartialMessageable it couldn't get from cache

2021-09-18 23:28 UTC, merged