add support for delete_after kwarg for interaction and webhook messages
iDevision/enhanced-discord.py pull request #79
Opened 2021-09-28 12:48 UTC by ethanolchik

## Summary
adds a `delete_message: Optional[float] = None` kwarg to `interaction.send_message` and `Webhook.send`.
adds a `delay: Optional[float] = None` parameter to `Interaction.delete_original_message`.

note: `delete_after` for `Webhook.send` will only work if `wait` kwarg is `True`.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-10-01 16:15 UTC, Gnome-py requested changes
Good idea, however needs to be reworked to act more like delete_after in ``Message.delete``

2021-10-01 16:15 UTC, Gnome-py commented on discord/interactions.py
> +            await asyncio.sleep(delay)
This is not done in the background as the docs say, please make it do.

2021-10-01 16:15 UTC, Gnome-py commented on discord/interactions.py
> +            self._parent.delete_original_message(delay=delete_after)
Needs ``await``

2021-10-01 16:15 UTC, Gnome-py commented on discord/interactions.py
>              asyncio.create_task(inner_call())
If you are modifying this to use delay in ``delete_original_message`` this shouldn't be in a task.

2021-10-01 16:15 UTC, Gnome-py commented on discord/webhook/async_.py
>              asyncio.create_task(inner_call())
If you are modifying this to use delay in ``delete_message`` this shouldn't be in a task.

2021-10-30 16:07 UTC, Soheab commented
@ethanolchik Please do the requested changes above.

2021-11-21 08:27 UTC, dfitzpatrick commented
Is this PR still alive?

2021-12-21 19:04 UTC, Gnome-py commented
Superseded by #117

2021-12-21 19:04 UTC, closed without merging